name: horizonflow
description: A task management and kanban tool built with Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.8.0
  flutter_dotenv: ^5.0.2
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  icons_launcher: ^2.1.0
  flutter_native_splash: ^2.2.19
  go_router: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/Rubik-Light.ttf
          weight: 300

icons_launcher:
  image_path: "assets/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:      
  color: "#4D7CFE"
  image: assets/logo_white.png